import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "@/lib/query";
export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, loading, error } = results;
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;
  console.log(data);
  return (
    <>
      <Head>
        <title>Styed Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Homepage</h1>
      </main>
    </>
  );
}
